Adding execution for state option
andrelnunes/COVID-19 pull request #16
Opened 2020-04-08 01:56 UTC by gdarruda

Hospital queue simulation is using all beds (icu and non-icu) of the cities for projections at state level.

2020-04-09 04:06 UTC, andrelnunes requested changes
Consegue revisar esses pontos e BUG do tempo de execução?

### BUG - Execução configurada para 180 dias e rodou por 200

<img width="1246" alt="Screen Shot 2020-04-09 at 01 01 20" src="https://user-images.githubusercontent.com/22736823/78856661-b5ae3080-79fd-11ea-80bb-d9bfc80cb1a5.png">

Console output:
<img width="448" alt="Screen Shot 2020-04-09 at 01 00 35" src="https://user-images.githubusercontent.com/22736823/78856597-91eaea80-79fd-11ea-9885-53c27258598f.png">

2020-04-09 04:06 UTC, andrelnunes commented on simulator/app.py
> +        href = make_download_href(ei_df, w_params, should_estimate_r0, r0_dist)
Esse era o parâmetro que estava quebrando download?

2020-04-09 04:06 UTC, andrelnunes commented on simulator/app.py
> +def make_EI_df(model_output, sample_size, date):
Essa data pode estar afetando o tempo de execução?

2020-04-09 12:32 UTC, gdarruda commented on simulator/app.py
> +        href = make_download_href(ei_df, w_params, should_estimate_r0, r0_dist)
> Consegue revisar esses pontos e BUG do tempo de execução?
> 
> ### BUG - Execução configurada para 180 dias e rodou por 200
> <img alt="Screen Shot 2020-04-09 at 01 01 20" width="1246" src="https://user-images.githubusercontent.com/22736823/78856661-b5ae3080-79fd-11ea-80bb-d9bfc80cb1a5.png">
> 
> Console output:
> <img alt="Screen Shot 2020-04-09 at 01 00 35" width="448" src="https://user-images.githubusercontent.com/22736823/78856597-91eaea80-79fd-11ea-9885-53c27258598f.png">

Vou confirmar hoje, mas isso pode acontecer porque a simulação começa a rodar com dados reais antes de entrar no período de 180 dias....então se não existe colapso roda-se com 180 dias + dias que há dados disponíveis de infectados.

2020-04-09 12:35 UTC, gdarruda commented on simulator/app.py
> +        href = make_download_href(ei_df, w_params, should_estimate_r0, r0_dist)
> Esse era o parâmetro que estava quebrando download?

Sim, esse parâmetro mesmo, estava acessando isso dentro do params...mas esse valor é calculado fora e na hora de gerar o JSON quebrava.

2020-04-13 02:34 UTC, andrelnunes approved these changes

2020-04-13 02:38 UTC, merged